// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NicolasCasamen_Examen1P.Data;

#nullable disable

namespace NicolasCasamen_Examen1P.Migrations
{
    [DbContext(typeof(NicolasCasamen_Examen1PContext))]
    [Migration("20240424160723_CambiosBdd")]
    partial class CambiosBdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NicolasCasamen_Examen1P.Models.NC_Cine", b =>
                {
                    b.Property<int>("NC_NumeroBoleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NC_NumeroBoleto"), 1L, 1);

                    b.Property<decimal>("NC_Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NC_Entradas")
                        .HasColumnType("int");

                    b.Property<DateTime>("NC_FechaPelicula")
                        .HasColumnType("datetime2");

                    b.Property<string>("NC_Pelicula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NC_Socio")
                        .HasColumnType("bit");

                    b.HasKey("NC_NumeroBoleto");

                    b.ToTable("NC_Cine");
                });
#pragma warning restore 612, 618
        }
    }
}
